import MainLayout from "../../components/MainLayout";
// import "@/src/styles/globals.css";
import Vazir from "next/font/local";
import "react-loading-skeleton/dist/skeleton.css";
import "../../styles/globals.css";

const vazir = Vazir({
  src: "../../assets/Vazir.woff2",
  display: "swap",
});

export const metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lang } }) {
  return (
    <html lang={lang} dir={lang === "fa-ir" || lang === "fa" ? "rtl" : "ltr"}>
      <body className={vazir.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
